GOMA_admin/urls.py
from django.urls import path
from GOMA_admin.views import (IndexAdminView, ClientesAdminView, ComprasAdminView, CategoriasAdminView, MarcasAdminView, EditarProductosView, EliminarProductosView, EliminarClientesView, EditarCategoriasView, EliminarCategoriasView, EditarMarcasView, EliminarMarcasView)

urlpatterns = [
    path('index_admin/', IndexAdminView.as_view(), name='index_admin'),
    path('usuarios/', ClientesAdminView.as_view(), name='usuarios'),
    path('compras/', ComprasAdminView.as_view(), name='compras'),
    path('categorias/', CategoriasAdminView.as_view(), name='categorias'),
    path('marcasAdmin/', MarcasAdminView.as_view(), name='marcasAdmin'),
    path('editar_producto/<int:producto_id>', EditarProductosView.as_view(), name='editar_producto'),
    path('eliminar_producto/<int:producto_id>', EliminarProductosView.as_view(), name='eliminar_producto'),
    path('eliminar_cliente/<int:cliente_id>', EliminarClientesView.as_view(), name='eliminar_cliente'),
    path('editar_categoria/<int:categoria_id>', EditarCategoriasView.as_view(), name='editar_categoria'),
    path('eliminar_categoria/<int:categoria_id>', EliminarCategoriasView.as_view(), name='eliminar_categoria'),
    path('editar_marca/<int:marca_id>', EditarMarcasView.as_view(), name='editar_marca'),
    path('eliminar_marca/<int:marca_id>', EliminarMarcasView.as_view(), name='eliminar_marca')
]

proyectofinal/urls.py
from django.contrib import admin
from django.urls import path, include
from GOMA.views import (IndexView, ProductosView, SobreNosotrosView, ProveedoresView, NuevoProductoView, 
AgregarProveedoresView, LoginView, SuperusuarioRegistroView, RegistroView, CerrarSesionView, BlogView, 
CrearNuevoBlogView, BuscarProductosView, ConfirmacionCompraView, ContactView)
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name="home"),
    path('productos/', ProductosView.as_view(), name="productos"),
    path('buscar_productos/', BuscarProductosView.as_view(), name='buscar_productos'),
    path('sobre_nosotros/', SobreNosotrosView.as_view(), name="sobre_nosotros"),
    path('proveedores/', ProveedoresView.as_view(), name="proveedores"),
    path('nuevo_producto/', NuevoProductoView.as_view(), name="nuevo_producto"),
    path('nuevo_proveedor/',AgregarProveedoresView.as_view(), name="nuevo_proveedor"),
    path('registrar/', RegistroView.as_view(), name="registrar"),
    path('registrar_super_usuario/', SuperusuarioRegistroView.as_view(), name="registrar_super_usuario"),
    path('iniciar_sesion/', LoginView.as_view(), name="iniciar_sesion"),
    path('cerrar_sesion/', CerrarSesionView.as_view(), name="cerrar_sesion"),
    path('blog/', BlogView.as_view(), name="blog"),
    path('crear_nuevo_blog/', CrearNuevoBlogView.as_view(), name="nuevo_blog"),
    path('confirmar_compra/', ConfirmacionCompraView.as_view(), name='confirmar_compra'),
    path('contact/', ContactView.as_view(), name='contact'),
    path('', include('GOMA_admin.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

GOMA/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User

# Create your models here.
class Marca(models.Model):
    nombre = models.CharField(max_length=200)
    
    def __str__(self):
        return self.nombre

class Categoria(models.Model):
    nombre = models.CharField(max_length=200)
    descripcion = models.TextField()
    
    def __str__(self):
        return self.nombre

class Proveedor(models.Model):
    nombre = models.CharField(max_length=200)
    direccion = models.CharField(max_length=200)
    telefono = models.CharField(max_length=20)
    marcas = models.ManyToManyField(Marca)
    
    def __str__(self):
        return "Proveedor: " + self.nombre + ", Contacto: Telefono " + self.telefono

class Producto(models.Model):
    nombre = models.CharField(max_length=200)
    descripcion = models.TextField()
    precio = models.DecimalField(max_digits=10, decimal_places=2)
    cantidad = models.IntegerField()
    disponibilidad = models.BooleanField(default=True)
    marca = models.ForeignKey(Marca, on_delete=models.CASCADE)
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)
    imagen = models.ImageField(upload_to="productos", null=True)
    
    def __str__(self):
        return self.nombre + " - " + "Cantidad: " + str(self.cantidad) + " unidades"

class Compra(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE, default='')
    nombreCompleto = models.CharField(max_length=100)
    email = models.EmailField()
    telefono = models.CharField(max_length=20)
    productos = models.ManyToManyField(Producto, through='CompraProducto')
    precioFinal = models.DecimalField(max_digits=10, decimal_places=2)
    fechaCompra = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f"Compra realizada por: {self.usuario.username} el día {self.fechaCompra.date()}"

class CompraProducto(models.Model):
    compra = models.ForeignKey(Compra, on_delete=models.CASCADE)
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    cantidad = models.IntegerField()
    
    def __str__(self):
        return f"Cliente: {self.compra.nombreCompleto} - Producto: {self.producto.nombre} - {self.cantidad} unidades"

class Post(models.Model):
    titulo = models.CharField(max_length=200)
    contenido = models.TextField()
    autor = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    fecha_creacion = models.DateTimeField(auto_now_add=True)
    fecha_actualizacion = models.DateTimeField(auto_now=True)
    imagen = models.ImageField(upload_to="posts", null=True, blank=True)

    def __str__(self):
        return self.titulo + " - Creado el: " + str(self.fecha_creacion.date())

GOMA_admin/models.py
from django.db import models

# Create your models here.

GOMA_admin/views.py
from django.contrib import messages
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views import View
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from GOMA.models import Producto, Compra, Marca, Categoria
from GOMA.mixins import AdminRequiredMixin
from GOMA.forms import ProductosForm, CategoriaForm, MarcaForm

# Create your views here.
class IndexAdminView(LoginRequiredMixin, AdminRequiredMixin, View):
    def get(self, request):
        productos = Producto.objects.all()
        return render(request, 'indexAdmin.html', {
            'productos' : productos
        })
        
class EditarProductosView(LoginRequiredMixin, AdminRequiredMixin, View):
    def get(self, request, producto_id):
        producto = get_object_or_404(Producto, pk=producto_id)
        form = ProductosForm(instance=producto)
        return render(request, 'editar_productos.html', {
            'producto': producto,
            'form': form
        })
        
    def post(self, request, producto_id):
        producto = get_object_or_404(Producto, pk=producto_id)
        form = ProductosForm(request.POST, request.FILES, instance=producto)
        if form.is_valid():
            form.save()
            messages.success(request, f"El producto {producto.nombre} se actualizó correctamente")
            return redirect('index_admin')
        else:
            return render(request, 'editar_productos.html', {
                'producto': producto,
                'form': form,
                'error': "Hubo un error al actualizar el producto"
            })
            
class EliminarProductosView(LoginRequiredMixin, AdminRequiredMixin, View):
    def get(self, request, producto_id):
        producto = get_object_or_404(Producto, pk=producto_id)
        producto.delete()
        return redirect('index_admin')
                
class ClientesAdminView(LoginRequiredMixin, AdminRequiredMixin, View):
    def get(self, request):
        clientes = User.objects.all()
        return render(request, 'clientes.html', {
            'clientes': clientes
        })
                    
class EliminarClientesView(LoginRequiredMixin, AdminRequiredMixin, View):
    def get(self, request, cliente_id):
        cliente = get_object_or_404(User, pk=cliente_id)
        cliente.delete()
        return redirect('usuarios')

class ComprasAdminView(LoginRequiredMixin, AdminRequiredMixin, View):
    def get(self, request):
        clientes_con_compras = User.objects.prefetch_related('compra_set__compraproducto_set').all()
        compras = Compra.objects.all()
        return render(request, 'compras.html', {
            'clientes_con_compras': clientes_con_compras,
            'compras': compras
        })
    
class MarcasAdminView(LoginRequiredMixin, AdminRequiredMixin, View):
    def get(self, request):
        marcas = Marca.objects.all()
        return render(request, 'marcasAdmin.html', {
            'marcas': marcas
        })

class EditarMarcasView(LoginRequiredMixin, AdminRequiredMixin, View):
    def get(self, request, marca_id):
        marca = get_object_or_404(Marca, pk=marca_id)
        form = MarcaForm(instance=marca)
        return render(request, 'editar_marcas.html', {
            'marca': marca,
            'form': form
        })

    def post(self, request, marca_id):
        marca = get_object_or_404(Marca, pk=marca_id)
        form = MarcaForm(request.POST, instance=marca)
        if form.is_valid():
            form.save()
            messages.success(request, f"La marca {marca.nombre} se actualizó correctamente")
            return redirect('marcasAdmin')
        else:
            return render(request, 'editar_marcas.html', {
                'marca': marca,
                'form': form,
                'error': "Hubo un error al actualizar la marca"
            })

class EliminarMarcasView(LoginRequiredMixin, AdminRequiredMixin, View):
    def get(self, request, marca_id):
        marca = get_object_or_404(Marca, pk=marca_id)
        marca.delete()
        messages.success(request, f"La marca {marca.nombre} se eliminó correctamente")
        return redirect('marcasAdmin')
    
class CategoriasAdminView(LoginRequiredMixin, AdminRequiredMixin, View):
    def get(self, request):
        categorias = Categoria.objects.all()
        return render(request, 'categorias.html', {
            'categorias' : categorias
        })
        
class EditarCategoriasView(LoginRequiredMixin, AdminRequiredMixin, View):
    def get(self, request, categoria_id):
        categoria = get_object_or_404(Categoria, pk=categoria_id)
        form = CategoriaForm(instance=categoria)
        return render(request, 'editar_categorias.html', {
            'categoria': categoria,
            'form': form
        })
                
    def post(self, request, categoria_id):
        categoria = get_object_or_404(Categoria, pk=categoria_id)
        form = CategoriaForm(request.POST, instance=categoria)
        if form.is_valid():
            form.save()
            messages.success(request, f"La categoria {categoria.nombre} se actualizó correctamente")
            return redirect('categorias')
        else:
            return render(request, 'editar_categorias.html', {
                'categoria': categoria,
                'form': form,
                'error': "Hubo un error al actualizar la categoria"
            })
            
class EliminarCategoriasView(LoginRequiredMixin, AdminRequiredMixin, View):
    def get(self, request, categoria_id):
        categoria = get_object_or_404(Categoria, pk=categoria_id)
        categoria.delete()
        messages.success(request, f"La marca {categoria.nombre} se eliminó correctamente")
        return redirect('categorias')

GOMA_admin/templates/categorias.html
{% extends 'layouts/baseAdmin.html' %}

{% block content %}

    <div class="contenedor__inicio">
        <div class="contenedor_titulo"> 
            <h1>Bienvenido {{ request.user.username }} al Panel para Administradores</h1>
        </div>
        <div class="container">
            {% if messages %}
                <div class="mensajes" style="margin-top: 6px;">
                    {% for message in messages %}
                        <h3 class="mensaje__Success">{{ message }}</h3>
                    {% endfor %}
                </div>
            {% endif %}
            <div class="table_header">
                <h2>Categorias</h2>
                <button><a href="{% url 'nuevo_proveedor' %}">Añadir Categoria</a></button>
            </div>
            <div class="table-responsive">
                <table class="display" id="MiTabla">
                    <thead>
                        <tr>
                            <th>ID <i class="bi bi-chevron-expand"></i></th>
                            <th>Categoria <i class="bi bi-chevron-expand"></i></th>
                            <th>Descripción <i class="bi bi-chevron-expand"></i></th>
                            <th>Acciones</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for categoria in categorias %}
                            <tr>
                                <td>{{ categoria.id }}</td>
                                <td>{{ categoria.nombre }}</td>
                                <td>{{ categoria.descripcion }}</td>
                                <td>
                                    <a href="{% url 'editar_categoria' categoria.id %}"><i class="bi bi-pencil-square" id="icons"></i></a>
                                    <a href="{% url 'eliminar_categoria' categoria.id %}"><i class="bi bi-trash3" id="icons"></i></a>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.7.0.js"></script>
    <script src="https://cdn.datatables.net/1.13.7/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.13.7/js/dataTables.bootstrap5.min.js"></script>
    <script>
        $(document).ready(function() {
            $('#MiTabla').DataTable({
                "order": [[1, "asc"]],
                "language": {
                    "lengthMenu": "Mostrar _MENU_",
                    "info": "Mostrando página _PAGE_ de _PAGES_",
                    "infoEmpty": "No hay registros disponibles",
                    "infoFiltered": "(Filtrada de _MAX_ Registros)",
                    "loadingRecords": "Cargando...",
                    "processing": "Procesando...",
                    "search": "Buscar:",
                    "zeroRecords": "No se encontraron registros coincidentes",
                    "paginate": {
                        "next": "Siguiente",
                        "previous": "Anterior"
                    },
                },
            });
        }); 
    </script>

{% endblock %}

GOMA_admin/templates/clientes.html
{% extends 'layouts/baseAdmin.html' %}

{% block content %}

    <div class="contenedor__inicio">
        <div class="contenedor_titulo">
            <h1>Bienvenido {{ request.user.username }} al Panel para Administradores</h1>
        </div>
        <div class="container">
            <div class="table_header">
                <h2>Usuarios</h2>
            </div>
            <div class="table-responsive">
                <table class="display" id="MiTabla">
                    <thead>
                        <tr>
                            <th>Usuario <i class="bi bi-chevron-expand"></i></th>
                            <th>Email <i class="bi bi-chevron-expand"></i></th>
                            <th>Fecha Registro <i class="bi bi-chevron-expand"></i></th>
                            <th>Último Login <i class="bi bi-chevron-expand"></i></th>
                            <th>Superusuario <i class="bi bi-chevron-expand"></i></th>
                            <th>Staff <i class="bi bi-chevron-expand"></i></th>
                            <th>Acciones</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for cliente in clientes %}
                                <tr>
                                <td>{{ cliente.username }}</td>
                                <td>{{ cliente.email }}</td>
                                <td>{{ cliente.date_joined }}</td>
                                <td>{{ cliente.last_login }}</td>
                                <td>
                                    {% if cliente.is_superuser == False %}
                                        <i class="bi bi-x-circle-fill" style="color: #FF0000;"></i>
                                    {% else %}
                                        <i class="bi bi-check-circle-fill" style="color: #0FFF00;"></i>
                                    {% endif %}
                                </td>
                                <td>
                                    {% if cliente.is_staff == False %}
                                        <i class="bi bi-x-circle-fill" style="color: #FF0000;"></i>
                                    {% else %}
                                        <i class="bi bi-check-circle-fill" style="color: #0FFF00;"></i>
                                    {% endif %}
                                </td>
                                <td>
                                    <a href="{% url 'eliminar_cliente' cliente.id %}"><i class="bi bi-trash3" id="icons"></i></a>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.7.0.js"></script>
    <script src="https://cdn.datatables.net/1.13.7/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.13.7/js/dataTables.bootstrap5.min.js"></script>
    <script>
        $(document).ready(function() {
            $('#MiTabla').DataTable({
                "order": [[1, "asc"]],
                "language": {
                    "lengthMenu": "Mostrar _MENU_",
                    "info": "Mostrando página _PAGE_ de _PAGES_",
                    "infoEmpty": "No hay registros disponibles",
                    "infoFiltered": "(Filtrada de _MAX_ Registros)",
                    "loadingRecords": "Cargando...",
                    "processing": "Procesando...",
                    "search": "Buscar:",
                    "zeroRecords": "No se encontraron registros coincidentes",
                    "paginate": {
                        "next": "Siguiente",
                        "previous": "Anterior"
                    },
                },
            });
        }); 
    </script>

{% endblock %}

GOMA_admin/templates/compras.html
{% extends 'layouts/baseAdmin.html' %}

{% block content %}

    <div class="contenedor__inicio">
        <div class="contenedor_titulo">
            <h1>Bienvenido {{ request.user.username }} al Panel para Administradores</h1>
        </div>
        <div class="container">
            <div class="table_header">
                <h2>Compras</h2>
            </div>
            <div class="table-responsive">
                <table class="display" id="MiTabla">
                    <thead>
                        <tr>
                            <th>Cliente <i class="bi bi-chevron-expand"></i></th>
                            <th>Email <i class="bi bi-chevron-expand"></i></th>
                            <th>Telefono <i class="bi bi-chevron-expand"></i></th>
                            <th>Cantidad Productos <i class="bi bi-chevron-expand"></i></th>
                            <th>Productos <i class="bi bi-chevron-expand"></i></th>
                            <th>Precio Total <i class="bi bi-chevron-expand"></i></th>
                            <th>Fecha de Compra <i class="bi bi-chevron-expand"></i></th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for cliente in clientes_con_compras %}
                            {% if cliente.compra_set.exists %}
                                {% for compra in cliente.compra_set.all %}
                                    <tr>
                                        <td>{{ cliente.username }}</td>
                                        <td>{{ cliente.email }}</td>
                                        <td>{{ compra.telefono }}</td>
                                        <td>
                                            {% for compra in cliente.compra_set.all %}
                                                {{ compra.compraproducto_set.count }}
                                                {% if not forloop.last %}, {% endif %}
                                            {% endfor %}
                                        </td>
                                        <td>
                                            {% for compraproducto in compra.compraproducto_set.all %}
                                                {{ compraproducto.producto.nombre }}
                                                {% if not forloop.last %}, {% endif %}
                                            {% endfor %}
                                        </td>
                                        <td>{{ compra.precioFinal }}</td>
                                        <td>{{ compra.fechaCompra }}</td>
                                    </tr>
                                {% endfor %}
                            {% endif %}
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.7.0.js"></script>
    <script src="https://cdn.datatables.net/1.13.7/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.13.7/js/dataTables.bootstrap5.min.js"></script>
    <script>
        $(document).ready(function() {
            $('#MiTabla').DataTable({
                "order": [[1, "asc"]],
                "language": {
                    "lengthMenu": "Mostrar _MENU_",
                    "info": "Mostrando página _PAGE_ de _PAGES_",
                    "infoEmpty": "No hay registros disponibles",
                    "infoFiltered": "(Filtrada de _MAX_ Registros)",
                    "loadingRecords": "Cargando...",
                    "processing": "Procesando...",
                    "search": "Buscar:",
                    "zeroRecords": "No se encontraron registros coincidentes",
                    "paginate": {
                        "next": "Siguiente",
                        "previous": "Anterior"
                    },
                },
            });
        }); 
    </script>

{% endblock %}

GOMA_admin/templates/editar_categorias.html
{% extends 'layouts/baseAdminEditar.html' %}

{% block content %}

    <div class="contenedor__formularios" style="margin-top: 140px; margin-bottom: 60px;">        
        <div>
            <h1>Editar Categoria</h1>
            {% if error %}
                <h3 class="mensaje__Error">{{ error }}</h3>
            {% endif %}
        </div>
        <form action="" method="POST">
            {% csrf_token %}
            {{ form }}
            <button type="submit" name="categoria_form">Guardar</button>
            <button><a href="{% url 'index_admin' %}" style="text-decoration: none; color: #fff;">Cancelar</a></button>
        </form>
    </div>

{% endblock %}

GOMA_admin/templates/editar_marcas.html
{% extends 'layouts/baseAdminEditar.html' %}

{% block content %}

    <div class="contenedor__formularios" style="margin-top: 140px; margin-bottom: 60px;">        
        <div>
            <h1>Editar Marca</h1>
            {% if error %}
                <h3 class="mensaje__Error">{{ error }}</h3>
            {% endif %}
        </div>
        <form action="" method="POST">
            {% csrf_token %}
            {{ form }}
            <button type="submit" name="categoria_form">Guardar</button>
            <button><a href="{% url 'index_admin' %}" style="text-decoration: none; color: #fff;">Cancelar</a></button>
        </form>
    </div>

{% endblock %}

GOMA_admin/templates/editar_productos.html
{% extends 'layouts/baseAdminEditar.html' %}

{% block content %}
    <div class="contenedor__formularios" style="margin-top: 140px; margin-bottom: 60px;">
        <div>
            <h1>Editar Producto</h1>
            {% if error %}
                <h3 class="mensaje__Error">{{ error }}</h3>
            {% endif %}
        </div>
        <form action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="input-group">
                <label for="nombre">Nombre:</label>
                {{ form.nombre }}
            </div>
            <div class="input-group">
                <label for="descripcion">Descripción:</label>
                {{ form.descripcion }}
            </div>
            <div class="input-group">
                <label for="precio">Precio:</label>
                {{ form.precio }}
            </div>
            <div class="input-group">
                <label for="cantidad">Cantidad:</label>
                {{ form.cantidad }}
            </div>
            <div class="input-group">
                <label for="disponibilidad">Disponibilidad:</label>
                <div class="checkbox-container">
                    {{ form.disponibilidad }}
                </div>
            </div>        
            <div class="input-group">
                <label for="marca">Marca:</label>
                {{ form.marca }}
            </div>
            <div class="input-group">
                <label for="categoria">Categoría:</label>
                {{ form.categoria }}
            </div>
            <div class="input-group">
                <label for="imagen">Cambiar Imagen:</label>
                {% if producto.imagen %}
                    <img src="{{ producto.imagen.url }}" alt="{{ producto.nombre }}" style="max-width: 100px; max-height: 100px;">
                {% endif %}
                {{ form.imagen }}
            </div>
            <button class="btn-guardar">Guardar</button>
            <button><a href="{% url 'index_admin' %}" style="text-decoration: none; color: #fff;">Cancelar</a></button>
        </form>
    </div>
{% endblock %}

GOMA_admin/templates/indexAdmin.html
{% extends 'layouts/baseAdmin.html' %}

<link rel="stylesheet" href="https://cdn.datatables.net/1.13.7/css/dataTables.bootstrap5.min.css">

{% block content %}

    <div class="contenedor__inicio">
        <div class="contenedor_titulo">
            <h1>Bienvenido {{ request.user.username }} al Panel para Administradores</h1>
        </div>
        <div class="container">
            {% if messages %}
                <div class="mensajes" style="margin-top: 6px;">
                    {% for message in messages %}
                        <h3 class="mensaje__Success">{{ message }}</h3>
                    {% endfor %}
                </div>
            {% endif %}
            <div class="table_header">
                <h2>Productos</h2>
                <button><a href="{% url 'nuevo_producto' %}">Nuevo Producto</a></button>
            </div>
            <div class="table-responsive">
                <table class="display" id="MiTabla">
                    <thead>
                        <tr>
                            <th>Imagen <i class="bi bi-chevron-expand"></i></th>
                            <th>Nombre <i class="bi bi-chevron-expand"></i></th>
                            <th>Descripción <i class="bi bi-chevron-expand"></i></th>
                            <th>Cantidad <i class="bi bi-chevron-expand"></i></th>
                            <th>Disponible <i class="bi bi-chevron-expand"></i></th>
                            <th>Categoria <i class="bi bi-chevron-expand"></i></th>
                            <th>Marca <i class="bi bi-chevron-expand"></i></th>
                            <th>Acciones</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for producto in productos %}
                            <tr>
                                <td><img src="{{ producto.imagen.url }}" alt="{{ producto.imagen }}" width="50"></td>
                                <td>{{ producto.nombre }}</td>
                                <td>{{ producto.descripcion }}</td>
                                <td>{{ producto.cantidad }}</td>
                                <td>
                                    {% if producto.disponibilidad == False %}
                                        <i class="bi bi-x-circle-fill" style="color: #FF0000;"></i>
                                    {% else %}
                                        <i class="bi bi-check-circle-fill" style="color: #0FFF00;"></i>
                                    {% endif %}
                                </td>
                                <td>{{ producto.categoria }}</td>
                                <td>{{ producto.marca }}</td>
                                <td>
                                    <a href="{% url 'editar_producto' producto.id %}"><i class="bi bi-pencil-square" id="icons"></i></a>
                                    <a href="{% url 'eliminar_producto' producto.id %}"><i class="bi bi-trash3" id="icons"></i></a>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.7.0.js"></script>
    <script src="https://cdn.datatables.net/1.13.7/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.13.7/js/dataTables.bootstrap5.min.js"></script>
    <script>
        $(document).ready(function() {
            $('#MiTabla').DataTable({
                "order": [[1, "asc"]],
                "language": {
                    "lengthMenu": "Mostrar _MENU_",
                    "info": "Mostrando página _PAGE_ de _PAGES_",
                    "infoEmpty": "No hay registros disponibles",
                    "infoFiltered": "(Filtrada de _MAX_ Registros)",
                    "loadingRecords": "Cargando...",
                    "processing": "Procesando...",
                    "search": "Buscar:",
                    "zeroRecords": "No se encontraron registros coincidentes",
                    "paginate": {
                        "next": "Siguiente",
                        "previous": "Anterior"
                    },
                },
            });
        }); 
    </script>

{% endblock %}