GOMA_admin/urls.py
from django.urls import path
from GOMA_admin.views import (IndexAdminView, ClientesAdminView, ComprasAdminView, CategoriasAdminView, MarcasAdminView, EditarProductosView, EliminarProductosView, EliminarClientesView, EditarCategoriasView, EliminarCategoriasView, EditarMarcasView, EliminarMarcasView)

urlpatterns = [
    path('index_admin/', IndexAdminView.as_view(), name='index_admin'),
    path('usuarios/', ClientesAdminView.as_view(), name='usuarios'),
    path('compras/', ComprasAdminView.as_view(), name='compras'),
    path('categorias/', CategoriasAdminView.as_view(), name='categorias'),
    path('marcasAdmin/', MarcasAdminView.as_view(), name='marcasAdmin'),
    path('editar_producto/<int:producto_id>', EditarProductosView.as_view(), name='editar_producto'),
    path('eliminar_producto/<int:producto_id>', EliminarProductosView.as_view(), name='eliminar_producto'),
    path('eliminar_cliente/<int:cliente_id>', EliminarClientesView.as_view(), name='eliminar_cliente'),
    path('editar_categoria/<int:categoria_id>', EditarCategoriasView.as_view(), name='editar_categoria'),
    path('eliminar_categoria/<int:categoria_id>', EliminarCategoriasView.as_view(), name='eliminar_categoria'),
    path('editar_marca/<int:marca_id>', EditarMarcasView.as_view(), name='editar_marca'),
    path('eliminar_marca/<int:marca_id>', EliminarMarcasView.as_view(), name='eliminar_marca')
]

proyectofinal/urls.py
from django.contrib import admin
from django.urls import path, include
from GOMA.views import (IndexView, ProductosView, SobreNosotrosView, ProveedoresView, NuevoProductoView, 
AgregarProveedoresView, LoginView, SuperusuarioRegistroView, RegistroView, CerrarSesionView, BlogView, 
CrearNuevoBlogView, BuscarProductosView, ConfirmacionCompraView, ContactView)
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name="home"),
    path('productos/', ProductosView.as_view(), name="productos"),
    path('buscar_productos/', BuscarProductosView.as_view(), name='buscar_productos'),
    path('sobre_nosotros/', SobreNosotrosView.as_view(), name="sobre_nosotros"),
    path('proveedores/', ProveedoresView.as_view(), name="proveedores"),
    path('nuevo_producto/', NuevoProductoView.as_view(), name="nuevo_producto"),
    path('nuevo_proveedor/',AgregarProveedoresView.as_view(), name="nuevo_proveedor"),
    path('registrar/', RegistroView.as_view(), name="registrar"),
    path('registrar_super_usuario/', SuperusuarioRegistroView.as_view(), name="registrar_super_usuario"),
    path('iniciar_sesion/', LoginView.as_view(), name="iniciar_sesion"),
    path('cerrar_sesion/', CerrarSesionView.as_view(), name="cerrar_sesion"),
    path('blog/', BlogView.as_view(), name="blog"),
    path('crear_nuevo_blog/', CrearNuevoBlogView.as_view(), name="nuevo_blog"),
    path('confirmar_compra/', ConfirmacionCompraView.as_view(), name='confirmar_compra'),
    path('contact/', ContactView.as_view(), name='contact'),
    path('', include('GOMA_admin.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

GOMA/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User

# Create your models here.
class Marca(models.Model):
    nombre = models.CharField(max_length=200)
    
    def __str__(self):
        return self.nombre

class Categoria(models.Model):
    nombre = models.CharField(max_length=200)
    descripcion = models.TextField()
    
    def __str__(self):
        return self.nombre

class Proveedor(models.Model):
    nombre = models.CharField(max_length=200)
    direccion = models.CharField(max_length=200)
    telefono = models.CharField(max_length=20)
    marcas = models.ManyToManyField(Marca)
    
    def __str__(self):
        return "Proveedor: " + self.nombre + ", Contacto: Telefono " + self.telefono

class Producto(models.Model):
    nombre = models.CharField(max_length=200)
    descripcion = models.TextField()
    precio = models.DecimalField(max_digits=10, decimal_places=2)
    cantidad = models.IntegerField()
    disponibilidad = models.BooleanField(default=True)
    marca = models.ForeignKey(Marca, on_delete=models.CASCADE)
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)
    imagen = models.ImageField(upload_to="productos", null=True)
    
    def __str__(self):
        return self.nombre + " - " + "Cantidad: " + str(self.cantidad) + " unidades"

class Compra(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE, default='')
    nombreCompleto = models.CharField(max_length=100)
    email = models.EmailField()
    telefono = models.CharField(max_length=20)
    productos = models.ManyToManyField(Producto, through='CompraProducto')
    precioFinal = models.DecimalField(max_digits=10, decimal_places=2)
    fechaCompra = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f"Compra realizada por: {self.usuario.username} el día {self.fechaCompra.date()}"

class CompraProducto(models.Model):
    compra = models.ForeignKey(Compra, on_delete=models.CASCADE)
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    cantidad = models.IntegerField()
    
    def __str__(self):
        return f"Cliente: {self.compra.nombreCompleto} - Producto: {self.producto.nombre} - {self.cantidad} unidades"

class Post(models.Model):
    titulo = models.CharField(max_length=200)
    contenido = models.TextField()
    autor = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    fecha_creacion = models.DateTimeField(auto_now_add=True)
    fecha_actualizacion = models.DateTimeField(auto_now=True)
    imagen = models.ImageField(upload_to="posts", null=True, blank=True)

    def __str__(self):
        return self.titulo + " - Creado el: " + str(self.fecha_creacion.date())

GOMA/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import JsonResponse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import View
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django.contrib.auth import login, logout, authenticate
from django.db import IntegrityError
from .models import Post, Producto, Marca, Categoria, Compra, CompraProducto
from .forms import ProductosForm, CreatePostForm, CategoriaForm, MarcaForm
from django.contrib import messages
from .mixins import AdminRequiredMixin
from django.core.mail import EmailMessage
from django.template.loader import render_to_string
from django.conf import settings
from django.urls import reverse

class IndexView(View):
    def get(self, request):
        return render(request, 'index.html')
    
class ContactView(View):
    def post(self, request):
        name = request.POST['name']
        email = request.POST['email']
        subject = request.POST['subject']
        message = request.POST['message']
        
        template = render_to_string('email_template.html', {
            'name' : name,
            'email' : email,
            'subject' : subject,
            'message' : message
        })
        
        email = EmailMessage(subject, template, settings.EMAIL_HOST_USER, ['soyjahirjesua04@gmail.com'])
        
        email.fail_silently = False
        email.send()
        
        messages.success(request, 'Se ha enviado el correo exitosamente!')
        return redirect('home')

class ProductosView(View):
    def get(self, request):
        productos = Producto.objects.all()
        return render(request, 'productos.html', {
            'productos': productos
        })

class SobreNosotrosView(View):
    def get(self, request):
        return render(request, 'sobre_nosotros.html')

class ProveedoresView(View):
    def get(self, request):
        return render(request, 'proveedores.html')

class NuevoProductoView(LoginRequiredMixin, AdminRequiredMixin, View):
    def get(self, request):
        return render(request, 'nuevo_producto.html', {
            'form': ProductosForm
        })

    def post(self, request):
        try:
            form = ProductosForm(request.POST, request.FILES)
            if form.is_valid():
                post = form.save(commit=False)
                post.save()
                if request.user.is_superuser and request.user.is_staff:
                    return redirect('index_admin')
                else:
                    return redirect('productos')
            else:
                return render(request, 'nuevo_producto.html', {
                    'form': form, 
                    'error': 'Por favor completa correctamente el formulario.'
                })
        except ValueError:
            return render(request, 'nuevo_producto.html', {
                'form' : ProductosForm,
                'error' : "Porfavor agregue datos válidos."
            })


class RegistroView(View):
    def get(self, request):
        form = UserCreationForm()
        return render(request, 'registro.html', {
            'formRegister': form
        })

    def post(self, request):
        username = request.POST.get('username')
        email = request.POST.get('email')
        password1 = request.POST.get('password1')
        password2 = request.POST.get('password2')

        if username and email and password1 and password2:
            if password1 == password2:
                try:
                    usuario = User.objects.create_user(username=username, email=email, password=password1)
                    usuario.save()
                    login(request, usuario)
                    return redirect('home')
                except IntegrityError:
                    return render(request, 'registro.html', {
                        'formRegister': UserCreationForm, 
                        'errorRegister': "El Usuario Ingresado YA Existe."
                    })
            else:
                return render(request, 'registro.html', {
                    'formRegister': UserCreationForm, 
                    'errorRegister': "Las Contraseñas NO Coinciden."
                })

        return render(request, 'registro.html', {
            'formRegister': UserCreationForm
        })

class SuperusuarioRegistroView(LoginRequiredMixin, AdminRequiredMixin, View):
    def get(self, request):
        form = UserCreationForm()
        return render(request, 'superusuario_registro.html', {
            'formRegister': form
        })

    def post(self, request):
        username = request.POST.get('username')
        email = request.POST.get('email')
        password1 = request.POST.get('password1')
        password2 = request.POST.get('password2')

        if username and password1 and password2:
            if password1 == password2:
                try:
                    user = User.objects.create_user(username=username, email=email, password=password1)
                    user.is_superuser = True
                    user.save()
                    return render(request, 'superusuario_registro.html', {
                        'formRegister': UserCreationForm,
                        'mensaje' : f'Superusuario {username} registrado correctamente.'
                    })
                except:
                    return render(request, 'superusuario_registro.html', {
                        'formRegister': UserCreationForm, 
                        'error': "Hubo un error al registrar el superusuario"
                    })
            else:
                return render(request, 'superusuario_registro.html', {
                    'formRegister': UserCreationForm, 
                    'error': "Las contraseñas no coinciden"
                })
        return render(request, 'superusuario_registro.html', {
            'formRegister': UserCreationForm
        })


class LoginView(View):
    def get(self, request):
        form_login = AuthenticationForm()
        error_message = request.GET.get('error')
        return render(request, 'inicio_sesion.html', {
            'formLogin': form_login,
            'errorLogin': error_message
        })

    def post(self, request):
        form_login = AuthenticationForm(request, request.POST)
        
        if form_login.is_valid():
            username = form_login.cleaned_data['username']
            password = form_login.cleaned_data['password']
            Usuario = authenticate(request, username=username, password=password)
            if Usuario is not None:
                if Usuario.is_superuser and Usuario.is_staff:
                    login(request, Usuario)
                    return redirect('index_admin')
                else:
                    login(request, Usuario)
                    return redirect('home')
            else:
                return render(request, 'inicio_sesion.html', {
                    'formLogin': form_login,
                    'errorLogin': 'Usuario o contraseña incorrectos'
                })
        else:
            return render(request, 'inicio_sesion.html', {
                'formLogin': form_login,
                'errorLogin': 'Usuario o contraseña incorrectos'
            })

class CerrarSesionView(LoginRequiredMixin, View):
    def get(self, request):
        logout(request)
        return redirect('home')

class BlogView(View):
    def get(self, request):
        posts = Post.objects.all().order_by('-id')
        return render(request, 'blog.html', {
            'posts': posts
        })

class CrearNuevoBlogView(LoginRequiredMixin, AdminRequiredMixin, View):
    def get(self, request):
        return render(request, 'crear_blog.html', {
            'form': CreatePostForm
        })

    def post(self, request):
        form = CreatePostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.autor = request.user
            post.save()
            return redirect('blog')
        else:
            return render(request, 'crear_blog.html', {
                'form': form, 
                'error': 'Por favor, complete correctamente el formulario.'
            })

class AgregarProveedoresView(LoginRequiredMixin, AdminRequiredMixin, View):
    def get(self, request):
        return render(request, 'agregar_proveedores.html', {
            'MarcaForm': MarcaForm(),
            'CategoriaForm' : CategoriaForm()
        })
    
    def post(self, request):
        if 'marca_form' in request.POST:
            formMarca = MarcaForm(request.POST)
            if formMarca.is_valid():
                formMarca = Marca.objects.create(nombre=request.POST['nombre'])
                formMarca.save()
                if request.user.is_superuser and request.user.is_staff:
                    return redirect('marcasAdmin')
                else:
                    return render(request, 'agregar_proveedores.html', {
                        'MarcaForm': MarcaForm(),
                        'CategoriaForm' : CategoriaForm(),
                        'mensajeMarca' : f'La marca {formMarca.nombre} se agrego correctamente.'
                    })
            else:
                return render(request, 'agregar_proveedores.html', {
                    'MarcaForm': MarcaForm(),
                    'CategoriaForm': CategoriaForm(),
                    'errorMarca': 'Por favor, complete correctamente el formulario de marca.'
                })
        elif 'categoria_form' in request.POST:
            formCategoria = CategoriaForm(request.POST)
            if formCategoria.is_valid():

GOMA/templates/agregar_proveedores.html
<!-- Esta es la página del blog aqui se agregaran novedades que haya como por ejemplo promociones, no modificar la 
    sintaxis de jinja ya establecida aqui, dentro de la carpeta templates iran los archivos HTML, los archivos CSS, JS
    e IMG irán en la carpeta static -->

<!-- Esto hace mención a que va a heredar el contenido de la página "base.html" -->
{% extends 'layouts/basePages.html' %}

{% block title %} Agregar Nuevos Proveedores {% endblock %}

{% block content %}

    <div class="contenedor__todo" style="margin-top: 100px; margin-bottom: 60px;">
        <div>
            <h1>Agregar Nuevos Proveedores</h1>
            <h3 class="mensaje__Error">{{ error }}</h3>
        </div>
        <div class="contenedor" style="display: flex;">
            <div class="contenedor__formularios">
                <h2>Nueva Marca</h2>
                <h3 class="mensaje__Success">{{ mensajeMarca }}</h3>
                <h3 class="mensaje__Error">{{ errorMarca }}</h3>
                {{ errorMarca }}
                <form action="" method="POST">
                    {% csrf_token %}
                    {{ MarcaForm }}
                    <button type="submit" name="marca_form">Agregar Marca</button>
                </form>
            </div> 
            <div class="contenedor__formularios">
                <h2>Nueva Categoria</h2>
                <h3 class="mensaje__Success">{{ mensajeCategoria }}</h3>
                <h3 class="mensaje__Error">{{ errorCategoria }}</h3>
                <form action="" method="POST">
                    {% csrf_token %}
                    {{ CategoriaForm }}
                    <button type="submit" name="categoria_form">Agregar Categoria</button>
                </form>
            </div>
        </div>
    </div>

{% endblock %}

GOMA/templates/blog.html
<!-- Esta es la página del blog aqui se agregaran novedades que haya como por ejemplo promociones, no modificar la 
    sintaxis de jinja ya establecida aqui, dentro de la carpeta templates iran los archivos HTML, los archivos CSS, JS
    e IMG irán en la carpeta static -->

<!-- Esto hace mención a que va a heredar el contenido de la página "base.html" -->
{% extends 'layouts/basePages.html' %}
{% load static %}

<!-- Aqui se modifica al titulo correspondiente de la página -->
{% block title %} Blog de Nuestra Empresa {% endblock %}

<!-- Indica el contenido, aquí ira todo lo correspondiente a la página principal, NO modificar la sintaxis jinja -->
{% block content %}

    <!-- Agregar la información, (MEJOREN LA ESTRUCTURA) -->
    
    <!-- De este modo los posts se van a agregar dinamicamente a través del bucle for -->
    
    <div class="container__post" style="margin-bottom: 40px;">
        <div class="container__posts">
            {% for post in posts %}
                <div class="blog-post">
                    <h2>{{ post.titulo }}</h2>
                    <img src="{{ post.imagen.url }}" alt="{{ post.imagen }}">
                    <p>{{ post.contenido }}</p>
                    <p><b>Fecha de Publicación: </b>{{ post.fecha_creacion|date:"j F, Y" }}</p>
                    <p><b>Publicado por: </b>{{ post.autor }}</p>
                    <a href="{% url 'productos' %}">Más información</a>
                </div>
            {% endfor %}
            <div class="seccion__boton">
                {% if request.user.is_authenticated and request.user.is_superuser %}
                    <br>
                    <a href="{% url 'nuevo_blog' %}">Agregar un Nuevo Post</a>
                {% endif %}
            </div>
        </div>
        <div class="container__comments">
            <div>
                <h2>Deja tu opinión aquí:</h2>
                <div id="disqus_thread"></div>
            </div>
        </div>
    </div>

    <script>
        (function() { // DON'T EDIT BELOW THIS LINE
        var d = document, s = d.createElement('script');
        s.src = 'https://comercializadoragoma.disqus.com/embed.js';
        s.setAttribute('data-timestamp', +new Date());
        (d.head || d.body).appendChild(s);
        })();
    </script>
    <noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>

{% endblock %}

GOMA/templates/confirmar_compra.html
<!-- Esta es la página de compra aqui ira un formulario el cual ya nos muestra los producros que hayan seleccionado, 
    no modificar la sintaxis de jinja ya establecida aqui, dentro de la carpeta templates iran los archivos HTML, 
    los archivos CSS, JS e IMG irán en la carpeta static -->

<!-- Esto hace mención a que va a heredar el contenido de la página "base.html" -->
{% extends 'layouts/basePages.html' %}

{% block title %} Confirmación de Compra {% endblock %}

{% block content %}

    <div class="contenedor__formularios" style="margin-top: 120px; margin-bottom: 60px;">
        <div class="contenedor__titulo">
            <h1>Muchas gracias por preferir a GOMA Comercializadora</h1>
        </div>
        <form id="productos-form" method="POST">
            {% csrf_token %}
            {% if error %}
                <h1 class="error">{{ error }}</h1>
            {% endif %}

            <div class="input-group">
                <label for="id_nombre_comprador">Nombre del comprador:</label><br>
                <input type="text" name="nombre_comprador" maxlength="100" class="form-control" placeholder="Nombre del comprador" required id="id_nombre_comprador">
            </div>
            <div class="input-group">
                <label for="id_correo">Correo electrónico:</label><br>
                <input type="email" name="correo" class="form-control" placeholder="Correo electrónico" required id="id_correo">
            </div>
            <div class="input-group">
                <label for="id_telefono">Número de teléfono:</label><br>
                <input type="text" name="telefono" maxlength="20" class="form-control" placeholder="Número de teléfono" required id="id_telefono">
            </div>
            <div class="input-group">
                <label for="cantidad">Cantidad:</label><br>
                <input type="text" name="cantidad_productos" class="form-control" id="cantidad_productos" readonly>
            </div>
            <div class="input-group">
                <label for="productos">Productos:</label><br>
                <input type="text" name="productos" class="form-control" id="productos" readonly>
            </div>
            <div class="input-group">
                <label for="id_precio_final">Precio final:</label><br>
                <input type="text" id="precio_final" name="precio_final" class="form-control" readonly>
            </div>
            <button type="submit" id="submit-btn">Comprar</button>
        </form>
    </div>

    <script>
        document.addEventListener('DOMContentLoaded', function() {
            const urlParams = new URLSearchParams(window.location.search);
            
            const productos = urlParams.get('productos');
            document.getElementById('productos').value = productos;

            const cantidades = urlParams.get('cantidades');
            document.getElementById('cantidad_productos').value = cantidades;
            
            const precioFinal = urlParams.get('precio_final');
            document.getElementById('precio_final').value = precioFinal;
        });
    </script>

{% endblock %}

GOMA/templates/crear_blog.html
<!-- Esta es la página para añadir un blog, no modificar la sintaxis de jinja ya establecida aqui, dentro de la 
    carpeta templates iran los archivos HTML, los archivos CSS, JS e IMG, irán en la carpeta static -->

<!-- Esto hace mención a que va a heredar el contenido de la página "base.html" -->
{% extends 'layouts/basePages.html' %}

<!-- Aqui se modifica al titulo correspondiente de la página -->
{% block title %} Agregar un Nuevo Post {% endblock %}

<!-- Indica el contenido, aquí ira todo lo correspondiente a la página principal, NO modificar la sintaxis jinja -->
{% block content %}

    <!-- Agregar la información, (MEJOREN LA ESTRUCTURA) -->
    <div class="contenedor__formularios" style="margin-top: 120px; margin-bottom: 80px;">
        <div>
            <h1>Crear un Nuevo Post</h1>
            <h3 class="mensaje__Error">{{ error }}</h3>
        </div>
        <form action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form }}
            <button>Publicar</button>
        </form>
    </div>

{% endblock %}

GOMA/templates/email_template.html
Mensaje: {{ message }}

Enviado por: {{ name }} desde la página oficial de GOMA Refacciones y Lubricantes

Email del Usuario: {{ email }}

GOMA/templates/inicio_sesion.html
<!-- Esta es la página principal de toda la aplicación web, no modificar la sintaxis de jinja ya establecida aqui,
    dentro de la carpeta templates iran los archivos HTML, los archivos CSS, JS e IMG irán en la carpeta static -->

<!-- Esto hace mención a que va a heredar el contenido de la página "base.html" -->
{% extends 'layouts/basePages.html' %}

<!-- Aqui se modifica al titulo correspondiente de la página -->
{% block title %} Inicia Sesión {% endblock %}

<!-- Indica el contenido, aquí ira todo lo correspondiente a la página principal, NO modificar la sintaxis jinja -->
{% block content %}

<!-- Agregar la información, (MEJOREN LA ESTRUCTURA) -->
    <div class="contenedor__formularios" style="margin-top: 60px; margin-bottom: 80px;">
        <div class="contenedor__formularios-login">
            <div>
                <h1>Iniciar Sesión</h1>
                
                {% if messages %}
                    {% for message in messages %} 
                        <h3 class="mensaje__Error">{{ message }}</h3>
                    {% endfor %}
                {% endif %}

                {% if errorLogin %}
                    <h3 class="mensaje__Error">{{ errorLogin }}</h3>
                {% endif %}
            </div>
            <form action="" method="POST">
                {% csrf_token %}
                <div>
                    <label>Nombre de Usuario</label>
                    {{ formLogin.username }}
                </div>
                <div>
                    <label>Contraseña</label>
                    {{ formLogin.password }}
                </div>
                <div>
                    <a href="{% url 'registrar' %}">No tienes una cuenta aún? Registrate</a><br>
                    <button>Iniciar Sesión</button>
                </div>
            </form>
        </div>
    </div>

{% endblock %}

GOMA/templates/nuevo_producto.html
<!-- Esta es la página del blog aqui se agregaran novedades que haya como por ejemplo promociones, no modificar la 
    sintaxis de jinja ya establecida aqui, dentro de la carpeta templates iran los archivos HTML, los archivos CSS, JS
    e IMG irán en la carpeta static -->

<!-- Esto hace mención a que va a heredar el contenido de la página "base.html" -->
{% extends 'layouts/basePages.html' %}

{% block title %} Nuevo Producto {% endblock %}

{% block content %}

    <div class="contenedor__formularios" style="margin-top: 140px; margin-bottom: 60px;">
        <div>
            <h1>Agregar Producto Nuevo</h1>
            <h3 class="mensaje__Error">{{ error }}</h3>
        </div>
        <form action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="input-group">
                <label for="nombre">Nombre:</label>
                {{ form.nombre }}
            </div>
            <div class="input-group">
                <label for="descripcion">Descripción:</label>
                {{ form.descripcion }}
            </div>
            <div class="input-group">
                <label for="precio">Precio:</label>
                {{ form.precio }}
            </div>
            <div class="input-group">
                <label for="cantidad">Cantidad:</label>
                {{ form.cantidad }}
            </div>
            <div class="input-group">
                <label for="disponibilidad">Disponibilidad:</label>
                <div class="checkbox-container">
                    {{ form.disponibilidad }}
                </div>
            </div>        
            <div class="input-group">
                <label for="marca">Marca:</label>
                {{ form.marca }}
            </div>
            <div class="input-group">
                <label for="categoria">Categoría:</label>
                {{ form.categoria }}
            </div>
            <div class="input-group">
                <label for="imagen">Imagen:</label>
                {{ form.imagen }}
            </div>
            <button class="btn-guardar">Guardar</button>
        </form>
    </div>

{% endblock %}

GOMA/templates/registro.html
<!-- Esta es la página principal de toda la aplicación web, no modificar la sintaxis de jinja ya establecida aqui,
    dentro de la carpeta templates iran los archivos HTML, los archivos CSS, JS e IMG irán en la carpeta static -->

<!-- Esto hace mención a que va a heredar el contenido de la página "base.html" -->
{% extends 'layouts/basePages.html' %}

<!-- Aqui se modifica al titulo correspondiente de la página -->
{% block title %} Registrate para ser Cliente {% endblock %}

<!-- Indica el contenido, aquí ira todo lo correspondiente a la página principal, NO modificar la sintaxis jinja -->
{% block content %}

<!-- Agregar la información, (MEJOREN LA ESTRUCTURA) -->
    <div class="contenedor__formularios" style="margin-top: 40px; margin-bottom: 80px;">
        <div class="contenedor__formularios-register">
            <div>
                <h1>Registrarse</h1>
                <h3 class="mensaje__Error">{{ errorRegister }}</h3>
            </div>
            <form action="" method="POST" autocomplete="off">
                {% csrf_token %}
                <div>
                    <label>Nombre de Usuario</label>
                    {{ formRegister.username }}
                </div>
                <div>
                    <label>Correo Electrónico</label>
                    <input type="email" id="email" name="email" required>
                </div>
                <div>
                    <label>Contraseña</label>
                    {{ formRegister.password1 }}
                </div>
                <div>
                    <label>Confirmar Contraseña</label>
                    {{ formRegister.password2 }}
                </div>
                <div>
                    <a href="{% url 'iniciar_sesion' %}">Ya tienes una cuenta? Inicia Sesión</a><br>
                    <button type="submit">Registrarse</button>
                </div>
            </form>
        </div>
    </div>
        
{% endblock %}